Repository statisticsnorway/ssb-pypitemplate, pull requests merged in 2023-11, with the labels that each got.

#32 Change 'project_name' to be required when creating project from template
  .github/workflows/tests.yml
  cookiecutter.json
Labels: cookiecutter

#34 Documentation updates
  README.md
  docs/index.md
  docs/quickstart.md
Labels: documentation

#35 Release 2023.11.15
  README.md
  docs/guide.md
  docs/index.md
  docs/quickstart.md
Labels: documentation, cookiecutter

#36 Require api-documentation for medium code quality level
  {{cookiecutter.project_name}}/pyproject.toml
Labels: build

#37 Release 2023.11.17
  README.md
  docs/guide.md
  docs/index.md
  docs/quickstart.md
Labels: documentation, cookiecutter
